"""CalibrationResult → profile YAML that `--profile` reads back unchanged.

An overlay in the latency/defaults.yaml schema: meta, variance (when
estimated), processing.<subtype>.{by_label, per_resource} — no distance, no
defaults blocks. `by_label` is keyed by physical AWS name (portable across the
Terraform and CloudFormation graphs of one stack); `per_resource` by node id
is used only when a name is ambiguous in the graph.
"""

from __future__ import annotations

from pathlib import Path

import yaml

from iacsim.latency.calibrate.calibrator import CalibrationResult


def write_profile(result: CalibrationResult, path: Path) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_header(result) + yaml.safe_dump(result.profile, sort_keys=False, width=100))
    return path


def _header(result: CalibrationResult) -> str:
    m = result.meta
    lines = [
        "# generated by iacsim calibrate — rung 2 (measured); edit freely or regenerate.",
        f"# source={m.get('source')}  window={m.get('window')}  generated_at={m.get('generated_at')}",
        "# by_label entries are keyed by physical AWS name and serve either IaC format of this stack;",
        f"# per_resource entries (ambiguous names only) are keyed by node id (format={m.get('format')}).",
        f"# {m.get('covered')} of {m.get('nodes_seen')} measurable nodes calibrated; the rest keep defaults.yaml.",
        "",
    ]
    return "\n".join(lines)
